CREATE DATABASE IF NOT EXISTS wordgaze;
USE wordgaze;

CREATE TABLE IF NOT EXISTS users (
    id_user int AUTO_INCREMENT PRIMARY KEY,
    first_name varchar(150) NOT NULL,
    surnames varchar(250) NOT NULL,
    email varchar(250) NOT NULL,
    username varchar(150) NOT NULL,
    password_user varchar(250) NOT NULL
);


CREATE TABLE english_spanish_words (
    id int AUTO_INCREMENT PRIMARY KEY,
    english_word VARCHAR(255) NOT NULL,
    spanish_word VARCHAR(255) NOT NULL,
    category VARCHAR(255)
);

INSERT INTO english_spanish_words (english_word, spanish_word, category) 
VALUES 
    ('Dog', 'Perro', 'Animals'),
    ('Cat', 'Gato', 'Animals'),
    ('Elephant', 'Elefante', 'Animals'),
    ('Giraffe', 'Jirafa', 'Animals'),
    ('Lion', 'León', 'Animals'),
    ('Tiger', 'Tigre', 'Animals'),
    ('Bear', 'Oso', 'Animals'),
    ('Monkey', 'Mono', 'Animals'),
    ('Horse', 'Caballo', 'Animals'),
    ('Deer', 'Ciervo', 'Animals'),
    ('Kangaroo', 'Canguro', 'Animals'),
    ('Rhino', 'Rinoceronte', 'Animals'),
    ('Hippopotamus', 'Hipopótamo', 'Animals'),
    ('Zebra', 'Cebra', 'Animals'),
    ('Wolf', 'Lobo', 'Animals'),
    ('Fox', 'Zorro', 'Animals'),
    ('Rabbit', 'Conejo', 'Animals'),
    ('Squirrel', 'Ardilla', 'Animals'),
    ('Mouse', 'Ratón', 'Animals'),
    ('Rat', 'Rata', 'Animals'),
    ('Hedgehog', 'Erizo', 'Animals'),
    ('Otter', 'Nutria', 'Animals'),
    ('Seal', 'Foca', 'Animals'),
    ('Whale', 'Ballena', 'Animals'),
    ('Dolphin', 'Delfín', 'Animals'),
    ('Shark', 'Tiburón', 'Animals'),
    ('Octopus', 'Pulpo', 'Animals'),
    ('Jellyfish', 'Medusa', 'Animals'),
    ('Crab', 'Cangrejo', 'Animals'),
    ('Lobster', 'Langosta', 'Animals'),
    ('Shrimp', 'Camarón', 'Animals'),
    ('Clam', 'Almeja', 'Animals'),
    ('Oyster', 'Ostra', 'Animals'),
    ('Snail', 'Caracol', 'Animals'),
    ('Butterfly', 'Mariposa', 'Animals'),
    ('Bee', 'Abeja', 'Animals'),
    ('Ant', 'Hormiga', 'Animals'),
    ('Ladybug', 'Mariquita', 'Animals'),
    ('Spider', 'Araña', 'Animals'),
    ('Snake', 'Serpiente', 'Animals'),
    ('Lizard', 'Lagarto', 'Animals'),
    ('Crocodile', 'Cocodrilo', 'Animals'),



    ('Red', 'Rojo', 'Colors'),
    ('Blue', 'Azul', 'Colors'),
    ('Yellow', 'Amarillo', 'Colors'),
    ('Green', 'Verde', 'Colors'),
    ('Orange', 'Naranja', 'Colors'),
    ('Purple', 'Morado', 'Colors'),
    ('Pink', 'Rosa', 'Colors'),
    ('Black', 'Negro', 'Colors'),
    ('White', 'Blanco', 'Colors'),
    ('Gray', 'Gris', 'Colors'),


    ('Bed', 'Cama', 'Home'),
    ('Chair', 'Silla', 'Home'),
    ('Sofa', 'Sofá', 'Home'),
    ('Table', 'Mesa', 'Home'),
    ('Lamp', 'Lámpara', 'Home'),
    ('Rug', 'Tapete', 'Home'),
    ('Mirror', 'Espejo', 'Home'),
    ('Clock', 'Reloj', 'Home'),
    ('Picture', 'Cuadro', 'Home'),
    ('Bookshelf', 'Estantería', 'Home'),
    ('TV', 'Televisión', 'Home'),
    ('Computer', 'Computadora', 'Home'),
    ('Phone', 'Teléfono', 'Home'),
    ('Refrigerator', 'Refrigerador', 'Home'),
    ('Oven', 'Horno', 'Home'),
    ('Stove', 'Estufa', 'Home'),
    ('Microwave', 'Microondas', 'Home'),
    ('Dishwasher', 'Lavavajillas', 'Home'),
    ('Sink', 'Fregadero', 'Home'),
    ('Toilet', 'Inodoro', 'Home'),
    ('Shower', 'Ducha', 'Home'),
    ('Bathtub', 'Bañera', 'Home'),
    ('Towel', 'Toalla', 'Home'),
    ('Soap', 'Jabón', 'Home'),
    ('Shampoo', 'Champú', 'Home'),
    ('Toothbrush', 'Cepillo de dientes', 'Home'),
    ('Toothpaste', 'Pasta de dientes', 'Home'),


    ('Apple', 'Manzana', 'Food'),
    ('Banana', 'Plátano', 'Food'),
    ('Orange', 'Naranja', 'Food'),
    ('Strawberry', 'Fresa', 'Food'),
    ('Grape', 'Uva', 'Food'),
    ('Watermelon', 'Sandía', 'Food'),
    ('Pineapple', 'Piña', 'Food'),
    ('Mango', 'Mango', 'Food'),
    ('Peach', 'Durazno', 'Food'),
    ('Pear', 'Pera', 'Food'),
    ('Lemon', 'Limón', 'Food'),
    ('Lime', 'Limón verde', 'Food'),
    ('Cherry', 'Cereza', 'Food'),
    ('Blueberry', 'Arándano azul', 'Food'),
    ('Raspberry', 'Frambuesa', 'Food'),
    ('Blackberry', 'Mora', 'Food'),
    ('Cranberry', 'Arándano rojo', 'Food'),
    ('Tomato', 'Tomate', 'Food'),
    ('Potato', 'Papa', 'Food'),
    ('Carrot', 'Zanahoria', 'Food'),
    ('Onion', 'Cebolla', 'Food'),
    ('Garlic', 'Ajo', 'Food'),
    ('Broccoli', 'Brócoli', 'Food'),
    ('Cauliflower', 'Coliflor', 'Food'),
    ('Cabbage', 'Repollo', 'Food'),
    ('Lettuce', 'Lechuga', 'Food'),
    ('Spinach', 'Espinaca', 'Food'),
    ('Kale', 'Col rizada', 'Food'),
    ('Peas', 'Guisantes', 'Food'),
    ('Beans', 'Frijoles', 'Food'),
    ('Corn', 'Maíz', 'Food'),
    ('Rice', 'Arroz', 'Food'),
    ('Bread', 'Pan', 'Food'),
    ('Pasta', 'Pasta', 'Food'),
    ('Chicken', 'Pollo', 'Food'),
    ('Beef', 'Carne de vaca', 'Food'),
    ('Pork', 'Carne de cerdo', 'Food'),
    ('Fish', 'Pescado', 'Food'),
    ('Shrimp', 'Camarón', 'Food'),
    ('Crab', 'Cangrejo', 'Food'),
    ('Lobster', 'Langosta', 'Food'),
    ('Cheese', 'Queso', 'Food'),
    ('Milk', 'Leche', 'Food'),
    ('Yogurt', 'Yogur', 'Food'),
    ('Ice cream', 'Helado', 'Food'),

    ('Football', 'Fútbol americano', 'Sports'),
    ('Basketball', 'Baloncesto', 'Sports'),
    ('Baseball', 'Béisbol', 'Sports'),
    ('Hockey', 'Hockey', 'Sports'),
    ('Soccer', 'Fútbol', 'Sports'),
    ('Tennis', 'Tenis', 'Sports'),
    ('Golf', 'Golf', 'Sports'),
    ('Swimming', 'Natación', 'Sports'),
    ('Running', 'Correr', 'Sports'),
    ('Cycling', 'Ciclismo', 'Sports'),
    ('Gymnastics', 'Gimnasia', 'Sports'),
    ('Wrestling', 'Lucha libre', 'Sports'),
    ('Boxing', 'Boxeo', 'Sports'),
    ('Martial arts', 'Artes marciales', 'Sports'),
    ('Yoga', 'Yoga', 'Sports'),


    ('Sun', 'Sol', 'Nature'),
    ('Moon', 'Luna', 'Nature'),
    ('Stars', 'Estrellas', 'Nature'),
    ('Sky', 'Cielo', 'Nature'),
    ('Cloud', 'Nube', 'Nature'),
    ('Rain', 'Lluvia', 'Nature'),
    ('Snow', 'Nieve', 'Nature'),
    ('Wind', 'Viento', 'Nature'),
    ('Ocean', 'Océano', 'Nature'),
    ('Beach', 'Playa', 'Nature'),
    ('River', 'Río', 'Nature'),
    ('Lake', 'Lago', 'Nature'),
    ('Mountain', 'Montaña', 'Nature'),
    ('Tree', 'Árbol', 'Nature'),
    ('Flower', 'Flor', 'Nature'),
    ('Grass', 'Hierba', 'Nature'),
    ('Rock', 'Roca', 'Nature'),
    ('Earth', 'Tierra', 'Nature'),
    ('Fire', 'Fuego', 'Nature'),
    ('Ice', 'Hielo', 'Nature'),
    ('Thunder', 'Trueno', 'Nature'),
    ('Lightning', 'Relámpago', 'Nature'),
    ('Tornado', 'Tornado', 'Nature'),
    ('Hurricane', 'Huracán', 'Nature'),
    ('Volcano', 'Volcán', 'Nature'),
    ('Glacier', 'Glaciar', 'Nature'),

    ('Doctor', 'Doctor', 'Profession'),
    ('Teacher', 'Profesor/a', 'Profession'),
    ('Engineer', 'Ingeniero/a', 'Profession'),
    ('Lawyer', 'Abogado/a', 'Profession'),
    ('Nurse', 'Enfermero/a', 'Profession'),
    ('Architect', 'Arquitecto/a', 'Profession'),
    ('Programmer', 'Programador/a', 'Profession'),
    ('Designer', 'Diseñador/a', 'Profession'),
    ('Scientist', 'Científico/a', 'Profession'),
    ('Writer', 'Escritor/a', 'Profession'),
    ('Actor', 'Actor/actriz', 'Profession'),
    ('Musician', 'Músico/a', 'Profession'),
    ('Chef', 'Chef/cocinero', 'Profession'),
    ('Athlete', 'Atleta/deportista', 'Profession'),
    ('Pilot', 'Piloto', 'Profession'),
    ('Artist', 'Artista', 'Profession'),
    ('Dentist', 'Dentista', 'Profession'),
    ('Psychologist', 'Psicólogo/a', 'Profession'),
    ('Journalist', 'Periodista', 'Profession'),


    ('Car', 'Coche', 'Transport'),
    ('Bicycle', 'Bicicleta', 'Transport'),
    ('Motorcycle', 'Motocicleta', 'Transport'),
    ('Bus', 'Autobús', 'Transport'),
    ('Train', 'Tren', 'Transport'),
    ('Subway', 'Metro', 'Transport'),
    ('Boat', 'Barco', 'Transport'),
    ('Ship', 'Nave', 'Transport'),
    ('Airplane', 'Avión', 'Transport'),
    ('Helicopter', 'Helicóptero', 'Transport'),
    ('Rocket', 'Cohete', 'Transport'),

    ('Shirt', 'Camisa', 'Clothing'),
    ('T-shirt', 'Camiseta', 'Clothing'),
    ('Pants', 'Pantalones', 'Clothing'),
    ('Jeans', 'Vaqueros', 'Clothing'),
    ('Shorts', 'Pantalones cortos', 'Clothing'),
    ('Skirt', 'Falda', 'Clothing'),
    ('Dress', 'Vestido', 'Clothing'),
    ('Suit', 'Traje', 'Clothing'),
    ('Jacket', 'Chaqueta', 'Clothing'),
    ('Coat', 'Abrigo', 'Clothing'),
    ('Sweater', 'Jersey', 'Clothing'),
    ('Hoodie', 'Sudadera con capucha', 'Clothing'),
    ('Socks', 'Calcetines', 'Clothing'),
    ('Shoes', 'Zapatos', 'Clothing'),
    ('Sneakers', 'Zapatillas', 'Clothing'),
    ('Boots', 'Botas', 'Clothing');




CREATE TABLE verbos_irregulares (
    id_verbos INT AUTO_INCREMENT PRIMARY KEY,
    infinitivo VARCHAR(255) NOT NULL,
    pasado_simple VARCHAR(255) NOT NULL,
    participio_pasado VARCHAR(255) NOT NULL,
    traduccion VARCHAR(255) NOT NULL
);

INSERT INTO irregulars_verbs (infinitive, simple_past, past participle, translation) VALUES
    ('be', 'was / were', 'been', 'ser/estar'),
    ('begin', 'began', 'begun', 'comenzar'),
    ('bite', 'bit', 'bitten', 'morder'),
    ('break', 'broke', 'broken', 'romper'),
    ('bring', 'brought', 'brought', 'traer'),
    ('build', 'built', 'built', 'construir'),
    ('buy', 'bought', 'bought', 'comprar'),
    ('catch', 'caught', 'caught', 'atrapar'),
    ('choose', 'chose', 'chosen', 'elegir'),
    ('come', 'came', 'come', 'venir'),
    ('cost', 'cost', 'cost', 'costar'),
    ('cut', 'cut', 'cut', 'cortar'),
    ('do', 'did', 'done', 'hacer'),
    ('draw', 'drew', 'drawn', 'dibujar'),
    ('drive', 'drove', 'driven', 'conducir'),
    ('eat', 'ate', 'eaten', 'comer'),
    ('fall', 'fell', 'fallen', 'caer'),
    ('feel', 'felt', 'felt', 'sentir'),
    ('find', 'found', 'found', 'encontrar'),
    ('fly', 'flew', 'flown', 'volar'),
    ('forget', 'forgot', 'forgotten', 'olvidar'),
    ('get', 'got', 'got / gotten', 'obtener'),
    ('give', 'gave', 'given', 'dar'),
    ('go', 'went', 'gone', 'ir'),
    ('grow', 'grew', 'grown', 'crecer'),
    ('have', 'had', 'had', 'tener/haber'),
    ('hear', 'heard', 'heard', 'oir'),
    ('hide', 'hid', 'hidden', 'esconder'),
    ('hit', 'hit', 'hit', 'golpear'),
    ('hold', 'held', 'held', 'sostener'),
    ('hurt', 'hurt', 'hurt', 'herir'),
    ('keep', 'kept', 'kept', 'mantener'),
    ('know', 'knew', 'known', 'saber/conocer'),
    ('leave', 'left', 'left', 'dejar'),
    ('lend', 'lent', 'lent', 'prestar'),
    ('let', 'let', 'let', 'dejar'),
    ('lie', 'lay', 'lain', 'estar acostado'),
    ('lose', 'lost', 'lost', 'perder'),
    ('make', 'made', 'made', 'hacer/fabricar'),
    ('mean', 'meant', 'meant', 'significar'),
    ('meet', 'met', 'met', 'conocer/reunirse'),
    ('pay', 'paid', 'paid', 'pagar'),
    ('put', 'put', 'put', 'poner'),
    ('read', 'read', 'read', 'leer'),
    ('ride', 'rode', 'ridden', 'montar'),
    ('ring', 'rang', 'rung', 'sonar'),
    ('rise', 'rose', 'risen', 'levantarse'),
    ('run', 'ran', 'run', 'correr'),
    ('say', 'said', 'said', 'decir'),
    ('see', 'saw', 'seen', 'ver'),
    ('seek', 'sought', 'sought', 'buscar'),
    ('sell', 'sold', 'sold', 'vender'),
    ('send', 'sent', 'sent', 'enviar'),
    ('set', 'set', 'set', 'establecer'),
    ('shake', 'shook', 'shaken', 'agitar'),
    ('shine', 'shone', 'shone', 'brillar'),
    ('shoot', 'shot', 'shot', 'disparar'),
    ('show', 'showed', 'shown', 'mostrar'),
    ('shut', 'shut', 'shut', 'cerrar'),
    ('sing', 'sang', 'sung', 'cantar'),
    ('sink', 'sank', 'sunk', 'hundir'),
    ('sit', 'sat', 'sat', 'sentarse'),
    ('sleep', 'slept', 'slept', 'dormir'),
    ('speak', 'spoke', 'spoken', 'hablar'),
    ('spend', 'spent', 'spent', 'gastar'),
    ('stand', 'stood', 'stood', 'estar de pie'),
    ('steal', 'stole', 'stolen', 'robar'),
    ('swim', 'swam', 'swum', 'nadar'),
    ('take', 'took', 'taken', 'tomar'),
    ('teach', 'taught', 'taught', 'enseñar'),
    ('tear', 'tore', 'torn', 'romper'),
    ('tell', 'told', 'told', 'contar'),
    ('think', 'thought', 'thought', 'pensar'),
    ('throw', 'threw', 'thrown', 'lanzar'),
    ('understand', 'understood', 'understood', 'entender'),
    ('wake', 'woke', 'woken', 'despertar'),
    ('wear', 'wore', 'worn', 'llevar puesto'),
    ('win', 'won', 'won', 'ganar'),
    ('write', 'wrote', 'written', 'escribir');